# Catenator Structural Schema v0.1
# This schema validates the integrity of Macro, Meso, and Micro catens.

$schema: "http://json-schema.org/draft-07/schema#"
title: CatenatorLogicUnit
type: object
required: [metadata, logic]

properties:
  metadata:
    type: object
    required: [id, version, layer, intent, readiness_score]
    properties:
      id:
        type: string
        description: "Unique kebab-case identifier (e.g., auth-validator)."
      version:
        type: string
        pattern: "^v?\\d+\\.\\d+(\\.\\d+)?$"
        description: "Semantic versioning of the logic unit."
      layer:
        type: string
        enum: [macro, meso, micro]
        description: "The architectural depth of the caten."
      intent:
        type: string
        minLength: 10
        description: "Natural language description for ML indexing/RAG."
      tags:
        type: array
        items: { type: string }
      readiness_score:
        type: integer
        minimum: 1
        maximum: 5
      anchors:
        type: array
        items: { type: string }
        description: "References to global Macro standards."

  logic:
    type: object
    description: "The primary technical payload of the caten."
    properties:
      definitions:
        type: object
        description: "Static parameters or regex patterns."
      triggers:
        type: array
        items: 
          type: object
          required: [on, action]
          properties:
            on: { type: string }
            action: { type: string }
      links:
        type: array
        items:
          type: object
          required: [ref]
          properties:
            ref: { type: string, description: "Pointer to another caten/version." }
            alias: { type: string }

  exceptions:
    type: array
    items:
      type: object
      required: [condition, response]
      properties:
        condition: { type: string }
        response: { type: string }